sudo: required
language: generic 

services:
  - docker

before_install:

 - docker build -t smol-tok/react -f Dockerfile.dev .

script:
  - docker run -e CI=true smol-tok/react npm run test -- --coverage